[HTMLGenalouder][開発]画面　#33625
diesel141/htmlGenalouder pull request #4
Opened 2024-09-19 05:05 UTC by testJcSin

## 開発チケット
https://report.r-jc.jp/issues/33625
## 関連プルリク
なし
## 修正概要
[#33625 [HTMLGenalouder][開発]画面(https://report.r-jc.jp/issues/33625)
##修正内容
Gradioを使用して画面を作成する
・音声入力
・HTML生成結果出力
・履歴表示
## その他
・履歴は作成日の降順でソート（作成日が未設定の場合はソート最後で「日付不明」と表示）
・動作確認はモックで確認

2024-10-15 21:50 UTC, cucl2-similis commented on app/main.py
> +def render_row(date, input_text, output_html):
Flake8のエラーが出ているため確認お願い致します。
```
Flake8(E302)
expected 2 blank lines, found 1
```

2024-10-15 22:47 UTC, cucl2-similis requested changes
@testJcSin

ご確認のほど宜しくお願い致します。

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +def render_row(date, input_text, output_html):
Flake8のエラーが出ているため確認お願い致します。
```
Flake8(E302)
expected 2 blank lines, found 1
```

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +        # 音声入力エリア
Flake8のエラーが出ているため確認お願い致します。
```
Flake8(E115)
expected an indented block (comment)
```

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +            key=lambda model: model.created_at if model.created_at is not None else datetime.datetime.min,
Flake8の警告が2箇所とエラーが1箇所出ているためそれぞれ確認お願い致します。
```
Flake8(W291)
trailing whitespace

Flake8(E501)
line too long (106 > 79 characters)
```

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +        html_content += f'<tr><td style="word-wrap: break-word;">{model.prompt_ja}</td><td style="word-wrap: break-word;">{model.html}</td></tr>'
Flake8のエラーが出ているため確認お願い致します。
```
Flake8(E501)
line too long (145 > 79 characters)
```
（参考）長い文字列リテラルの整形に関しては Black Formatter の安定版に含まれず、
　　　　`"--unstable"`の指定が必要になるようでした。
> [The (future of the) Black code style > Preview style](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#labels-string-processing:~:text=The%20unstable%20style,see%20below%29)
>
> The unstable style additionally includes the following features:
> - `string_processing`: split long string literals and related changes ([see below](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html#labels-string-processing))

また、引用符を含む文字列について特に言及は無いものの、
基本的には二重引用符`""`が好まれるようなので、
HTMLタグの`style`属性を`''`としておく方が無難ではないかと思われます。
（f文字列もデフォルトでは`f""`にフォーマットされる。）
参考：[The Black code style > Code style > Strings](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#strings)

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +    html_button.click(fn=process_audio_to_html, inputs=audio_data, outputs=html_output)
Flake8のエラーが出ているため確認お願い致します。
```
Flake8(E501)
line too long (87 > 79 characters)
```
この行に関してはそのままだとフォーマットできないため、
変数名の長さを変えるなどして調整する必要があるかと思います。

デフォルトのフォーマッタに Black Formatter を使用（[settings.json](https://github.com/diesel141/htmlGenalouder/blob/main/.vscode/settings.json)）しており、  
Flake8とのデフォルト行長の差により、81～88文字のFlake8エラー行は整形されないためです。
参考：[The Black code style > Code style > Line length](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length)

また、[settings.json](https://github.com/diesel141/htmlGenalouder/blob/main/.vscode/settings.json) に `"black-formatter.args": ["--line-length=80"]` を追加し、
Black Formatter のデフォルト行長を Flake8 に合わせる方法も考えられますが、
プロジェクト全体のフォーマット設定を変更することになるため、確認の上ご検討お願い致します。
参考：[vscode-black-formatter > Settings](https://github.com/microsoft/vscode-black-formatter?tab=readme-ov-file#settings)
　　　[The basics > Usage > Command line options > `-l`, `--line-length`](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#l-line-length)

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +            render_row(date_str, model.prompt_ja, model.html)
このwith文は `python main.py` 呼び出し時に一度だけ実行され、
履歴タブの描画を行っているようです。
＝`history_service.get_all_histories()`が一度しか呼び出されず、
　以降は履歴タブ表示内容が更新されない。

そのためサーバ起動時点での履歴情報しか取得できず、
HTML生成ボタン押下（`process_audio_to_html(audio)`呼び出し）によって
新たに登録された情報は履歴に表示されないため、
最新の履歴を確認できるよう修正お願い致します。

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +        )
`HistoryDto`の並び順に関しては`HistoryService`の責務である気がしましたので、
こちらでメソッドを追加して連携しようと思いますがいかがでしょうか。

またその際、作成日時ではなくリクエストIDの降順で実装しても問題ないでしょうか。
「現在日付＋5桁0埋め」の連番をリクエストIDとして採番しているため、
基本的には作成日時と同じようになるはずですが、`main.py`にて何か特別な意図があって
作成日時の降順としているようであればご指摘お願い致します。

作成日時ではなくリクエストIDの降順としたい理由は下記の通りです。
- MySQLの`DATETIME`型は`'YYYY-MM-DD hh:mm:ss'`形式のため、
  1秒以内に複数回レコード登録された場合、
  作成日時の降順・リクエストIDの昇順といった出力になる可能性がある。
- 主キー`request_id`にはインデックスが設定されているため、
  `created_at`に比べ検索性能の向上が見込める。

2024-10-15 22:47 UTC, cucl2-similis commented on app/main.py
> +                else "日付不明"
`created_at`（作成日時）には NOT NULL 制約が指定されているため、`None`の考慮は不要です。

`created_at: datetime | None` としているのは、INSERT時のインスタンス生成に対応するためです。
（レコード挿入時に`created_at`未指定の場合は、INSERT実行時の現在日時が登録される。）
分かりにくく申し訳ありません。。

2024-10-17 02:01 UTC, testJcSin commented on app/main.py
> +        )
@cucl2-similis 
詳細にありがとうございます。
確かにmain側でソートするよりservice側でソートしたほうが良いかと思うので作成お願いします。
※作成日時をキーにした意図は新しいものが一番上にくるようにしたかっただけなので、それが実現できるならIDでも問題ありません。

2024-10-17 02:35 UTC, cucl2-similis commented on app/main.py
> +        )
@testJcSin 

ご回答いただきありがとうございます。
service側にソート処理を追加いたしました。#5

`history_service.get_all_histories(reverse_request_id=True)` に変更することで
降順に取得できるようになるかと思いますので、ご対応お願い致します。

2024-10-17 02:48 UTC, kengoma commented on app/main.py
> +    html_button.click(fn=process_audio_to_html, inputs=audio_data, outputs=html_output)
Flake8のlengthを88にするよりBlackのlengthを80にする方が都合良いですかね？（80文字前提でコード書いてきたから）
であれば、今回は上記の設定を`setting.json`に追加で良さそう

2024-10-17 06:39 UTC, cucl2-similis commented on app/main.py
> +    html_button.click(fn=process_audio_to_html, inputs=audio_data, outputs=html_output)
@kengoma 
ありがとうございます。Blackのlengthを80にして対応する方針とさせて頂きます。

@testJcSin 
#6 で `settings.json` を変更いたしました。

2024-11-03 06:41 UTC, cucl2-similis commented on app/main.py
> +            render_row(date_str, model.prompt_ja, model.html)
@testJcSin

[更新処理の追加](https://github.com/diesel141/htmlGenalouder/pull/4/commits/f1d99ab304d1e6c85d72c92e091d0d5962bf959d#diff-990f7e4140fab1ad82afc787505090b64d4024e63a891405cd9085e7e6b249ddR40-R46)による対応ありがとうございます。

ボタンクリックの度に更新処理は呼び出されているものの、
タブの表示を動的に更新するには [`@gr.render`](https://www.gradio.app/docs/gradio/render) を使用する必要があるようです。
参考：[Dynamic Apps with the Render Decorator](https://www.gradio.app/guides/dynamic-apps-with-render-decorator)

また、履歴タブ更新（履歴リスト取得）の呼び出しタイミングについて、
現在「HTML生成」ボタン押下時に設定して頂いているかと思いますが、
INSERT と SELECT が同じイベントによって発火される実装になっています。
`process_audio_to_html` と `update_history_tab` の実行順序は制御されていないため、
場合によっては `get_all_histories` → `register_history` となり、
生成した最新のHTMLが履歴に表示されないことがあります。
このため [`gradio.Tab.select(···)`](https://www.gradio.app/docs/gradio/tab#tab-select) を `triggers` に指定することで、
履歴タブが選択された時に最新の履歴を取得するのが良いのではないかと思いました。

以下、修正案です。ご参考にして頂ければと思います。
1. `update_history_tab()` の定義を `with gr.Tab("履歴"):` 下へ移動。
1. `update_history_tab()` の定義に `@gr.render` を付加。
1. `update_history_tab()` の契機に `gr.Tab("履歴")` の `select` を指定。
1. `html_button.click` の `fn` には `process_audio_to_html` のみを指定。
<details><summary>Sample</summary>
<pre>
<code>
    # 履歴画面
    with gr.Tab("履歴") as gr_tab:
        # HTML出力ボタンクリック時処理
        html_button.click(
            # HTML生成処理後、最新の履歴処理を取得
            fn=process_audio_to_html,
            inputs=audio_data,
            outputs=html_output
        )
        # クリアボタンクリック時処理
        clear.click(
            fn=clear_outputs,
            inputs=[],
            outputs=[html_output, audio_data]
        )
        # 履歴タブの更新処理
        @gr.render(triggers=[gr_tab.select])
        def update_history_tab():
            model_list = history_service.get_all_histories(reverse_request_id=True)
            for model in model_list:
                date_str = model.created_at.strftime("%Y/%m/%d %H:%M")
                render_row(date_str, model.prompt_ja, model.html)
</code>
</pre>
</details>

2024-11-12 02:58 UTC, cucl2-similis commented on app/main.py
> +            render_row(date_str, model.prompt_ja, model.html)
対応済：[174b698190a6af4a319a61aa954d277dab496204](https://github.com/diesel141/htmlGenalouder/pull/4/commits/174b698190a6af4a319a61aa954d277dab496204)

2024-11-12 02:59 UTC, cucl2-similis approved these changes

2024-11-12 09:39 UTC, kengoma approved these changes

2024-11-12 09:42 UTC, merged